# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RabitSlideMenuDemo0' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RabitSlideMenuDemo0
	pod 'Kingfisher', '7.2.4'
	pod 'Material', '3.1.8'
	pod 'IQKeyboardManagerSwift', '6.5.10'
	pod 'R.swift', '6.1.0'

  target 'RabitSlideMenuDemo0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
